[package]
name = "starkfpi"
version = "0.2.0"
edition = "2023_11"

[dependencies]
starknet = "2.9.2"
openzeppelin_access = "0.20.0"
openzeppelin_token = "0.20.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }

[dev-dependencies]
openzeppelin_utils = "0.20.0"
snforge_std = "0.35.1"

[[target.starknet-contract]]
casm = true

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
block_id.tag = "latest"